import test from 'node:test';
import assert from 'node:assert/strict';
import '../web/disaster-core.js';
const D=globalThis.DisasterCore,now=Date.now();
test('global distances cross the dateline and support all hemispheres',()=>{assert.ok(D.km({lat:0,lng:179},{lat:0,lng:-179})<225);assert.ok(D.valid({lat:-45,lng:-170}));assert.equal(D.km({lat:91,lng:0},{lat:0,lng:0}),null)});
test('earthquakes retain observed time, magnitude and underground depth without inventing water depth',()=>{const r=D.usgs({features:[{id:'a',properties:{time:now,mag:4.5,url:'https://earthquake.usgs.gov/a',title:'Test'},geometry:{coordinates:[-120,35,12]}}]})[0];assert.equal(r.depthKm,12);assert.equal(r.at,now);assert.equal(r.magnitude,4.5);assert.equal(r.closed,null);assert.equal(D.usgs({features:[{properties:{time:now,url:'javascript:alert(1)'},geometry:{coordinates:[0,0]}}]}).length,0)});
test('moving event uses most recent valid point and preserves closed date',()=>{const rows=D.eonet({events:[{id:'a',title:'Storm',closed:new Date(now).toISOString(),categories:[{id:'severeStorms'}],sources:[{url:'https://example.org/report'}],geometry:[{type:'Point',date:new Date(now).toISOString(),coordinates:[179,-15]},{type:'Point',date:new Date(now-86400000).toISOString(),coordinates:[170,-20]}]}]});assert.equal(rows[0].lng,179);assert.equal(rows[0].closed,now);assert.equal(rows[0].type,'storm')});
test('filtering and nearby sorting do not claim safety or revive expired observations',()=>{const rows=[{id:'old',type:'flood',lat:0,lng:0,at:now-31*86400000},{id:'far',type:'flood',lat:10,lng:10,at:now},{id:'near',type:'flood',lat:0,lng:1,at:now-1000}];assert.deepEqual(D.select(rows,{origin:{lat:0,lng:0},sort:'nearby',now}).map(x=>x.id),['near','far']);assert.equal(D.select(rows,{radius:500,now}).length,0);assert.deepEqual(D.select(rows,{origin:{lat:0,lng:0},radius:500,now}).map(x=>x.id),['near']);assert.equal(D.select(rows,{type:'earthquake',now}).length,0)});
test('GDACS parses flood publication separately from event period and excludes duplicate earthquake feeds',async()=>{const {DOMParser}=await import('linkedom');const xml='<rss><channel><item><title>Flood report</title><guid>FL123</guid><link>https://www.gdacs.org/report.aspx?eventid=123&amp;eventtype=FL</link><pubDate>Sun, 04 Oct 2026 01:00:00 GMT</pubDate><geo:lat>13.8</geo:lat><geo:long>100.7</geo:long><gdacs:eventtype>FL</gdacs:eventtype><gdacs:iscurrent>true</gdacs:iscurrent><gdacs:fromdate>Mon, 05 Oct 2026 01:00:00 GMT</gdacs:fromdate></item></channel></rss>';const rows=D.gdacs(xml,new DOMParser());assert.equal(rows[0].type,'flood');assert.equal(rows[0].reportTime,true);assert.equal(rows[0].at,Date.parse('Sun, 04 Oct 2026 01:00:00 GMT'));assert.match(rows[0].url,/eventtype=FL/);assert.equal(rows[0].closed,null);assert.equal(D.gdacs(xml.replace('<gdacs:eventtype>FL','<gdacs:eventtype>EQ'),new DOMParser()).length,0);assert.throws(()=>D.gdacs('<html>unavailable</html>',new DOMParser()))});
