import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {DOMParser,parseHTML} from 'linkedom';
const {window,document}=parseHTML(fs.readFileSync('web/index.html','utf8'));
Object.defineProperty(document,'baseURI',{value:'https://daytondeltap.github.io/flood-aid/'});
const storage=new Map(),requests=[];
const samples={rows:[{id:'node-8',osmId:8,type:'node',en:'Test Market',th:'ตลาดทดสอบ',lat:13.81,lng:100.73,kind:'store'}],retrievedAt:Date.now()};
const responseFor=url=>String(url).includes('/data/inventory.json')?{rows:[],providers:[]} : String(url).includes('/data/places-')?samples:String(url).includes('/data/flood.json')?{rows:[{id:'FL.1',name:'Test road',lat:13.811,lng:100.731,depth:12,observedAt:Date.now()}],history:[],retrievedAt:Date.now()}:String(url).includes('/api/reports')?{reports:[],signedIn:true}:String(url).includes('/api/destinations')?{destinations:[],signedIn:true}:String(url).includes('/api/route')?{routes:[{distance:2000,duration:300,coordinates:[[100.731,13.812],[100.73,13.81]]}]}:{current:{temperature_2m:29,weather_code:3,time:'2026-10-03T08:00',relative_humidity_2m:70,wind_speed_10m:5},hourly:{time:['2026-10-03T09:00'],precipitation:[2],precipitation_probability:[75]},daily:{time:['2026-10-03'],temperature_2m_min:[26],temperature_2m_max:[31],precipitation_sum:[4]}};
const dialog=document.querySelector('dialog');dialog.showModal=function(){this.open=true};dialog.close=function(){this.open=false};window.scrollTo=()=>{};window.HTMLElement.prototype.scrollIntoView=()=>{};
const fetcher=async(url,opts)=>{requests.push({url,opts});return Response.json(responseFor(url))};
class FormDataStub{constructor(form){this.items=[...form.querySelectorAll('[name]')].map(e=>[e.name||e.getAttribute('name'),e.value??''])}get(k){return this.items.find(x=>x[0]===k)?.[1]}[Symbol.iterator](){return this.items[Symbol.iterator]()}}
const sandbox={window,document,console,DOMParser,sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},URLSearchParams,clearTimeout:()=>{},navigator:{onLine:true},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setInterval:()=>0,setTimeout:()=>0,URL,Response,Request,AbortSignal,AbortController,Date,Math,JSON,Map,Set,Promise,Number,String,encodeURIComponent,fetch:fetcher,FormData:FormDataStub};
vm.createContext(sandbox);for(const file of ['config.js','core.js','app.js','upgrade.js','pages.js','inventory-core.js','inventory.js','stock-metadata.js','compact.js','google-map.js'])vm.runInContext(fs.readFileSync('web/'+file,'utf8'),sandbox,{filename:file});
const run=source=>vm.runInContext(source,sandbox);


test('Pages loads district snapshots under repository base path',async()=>{await new Promise(r=>setImmediate(r));assert.ok(requests.some(r=>String(r.url)==='https://daytondeltap.github.io/flood-aid/data/flood.json'));assert.ok(requests.some(r=>String(r.url).includes('/flood-aid/data/places-')));assert.ok(document.querySelector('#mapSettingsButton'));run("navigate('supplies')");assert.match(document.body.textContent,/Test Market/)});
test('Pages rejects shared writes without pretending to save',async()=>{await assert.rejects(run("apiJSON('/api/reports',{method:'POST'})"),/need a backend/);run('reportForm()');assert.match(dialog.textContent,/need a backend/);assert.equal(document.querySelector('#reportForm'),null)});
test('Google key entry is optional and default configuration contains no key',()=>{assert.equal(window.FLOODAID_CONFIG.googleMapsBrowserKey,'');run('mapSettings()');assert.ok(document.querySelector('#mapsKey'));assert.equal(document.querySelector('#mapsKey').type,'password');assert.match(dialog.textContent,/Maps JavaScript API/);assert.equal(window.GMAPReady,false)});

test('retailer inventory search renders unknown stock without external setup links',()=>{run("navigate('supplies')");assert.ok(document.querySelector('#inventoryPanel'));assert.match(document.querySelector('#inventoryPanel').textContent,/Stock unknown/);assert.ok(document.querySelector('#inventoryGPS'));assert.ok(document.querySelector('#inventorySearch'));assert.equal(document.querySelector('#inventoryPanel').querySelectorAll('a').length,0)});

test('historical map and sensor list use selected time beyond 24 hours',()=>{const old=Date.now()-5*86400000;run(`floodData={rows:[{id:'old',name:'Old road',lat:13.812,lng:100.731,depth:20,observedAt:${old}}],history:[],retrievedAt:Date.now()};navigate('map');setHistory(${old})`);assert.ok(Number(document.querySelector('#heatTime').getAttribute('min'))<Date.now()-4*86400000);assert.match(document.querySelector('#timeLabel').textContent,/ICT · Historical view/);assert.match(document.querySelector('.sensor-row').textContent,/20cm/);assert.equal(document.querySelector('.sensor-value').className.includes('stale'),false);run('action("heat-now")');assert.equal(document.querySelector('.sensor-value').className.includes('stale'),true);assert.match(document.querySelector('#heatStatus').textContent,/Gray = old/)});
test('district change clears old journey and key settings stay inside the app',()=>{run("accessTarget={lat:13.81,lng:100.73,label:'Old district'};historyAt=Date.now()-86400000;changeArea(1)");assert.equal(run('accessTarget'),null);assert.equal(run('historyAt'),null);run('mapSettings()');assert.ok(document.querySelector('#rememberMapsKey'));assert.equal(document.querySelector('.maps-setup'),null);dialog.close();run('changeArea(0)')});
test('Google overlay renders canvas and cm labels at historical time and cleans up on redraw',()=>{
 const panes={overlayLayer:document.createElement('div'),overlayMouseTarget:document.createElement('div')};
 const paint=[];const originalCreate=document.createElement.bind(document);
 document.createElement=(tag,...args)=>{const el=originalCreate(tag,...args);if(tag==='canvas')el.getContext=()=>({scale(){},createRadialGradient(){return {addColorStop(){}}},fillRect(){paint.push('heat')}});return el};
 class GMap{constructor(el,options){this.el=el;this.options=options;this.center=options.center;this.zoom=options.zoom}getCenter(){return {lat:()=>this.center.lat,lng:()=>this.center.lng}}getZoom(){return this.zoom}setCenter(c){this.center=c}setZoom(z){this.zoom=z}getDiv(){return {clientWidth:1000,clientHeight:600}}addListener(){}panTo(c){this.center=c}fitBounds(){}}
 class Overlay{setMap(map){if(this.map)this.onRemove();this.map=map;if(map){this.onAdd();this.draw()}}getMap(){return this.map}getPanes(){return panes}getProjection(){return {fromLatLngToDivPixel:p=>({x:p.lng()*1000,y:p.lat()*-1000})}}}
 class Shape{setMap(){}addListener(){}}
 const sdk={maps:{Map:GMap,OverlayView:Overlay,Circle:Shape,Polyline:Shape,LatLng:class{constructor(lat,lng){this.a=lat;this.b=lng}lat(){return this.a}lng(){return this.b}},ControlPosition:{RIGHT_BOTTOM:1},event:{clearInstanceListeners(){}}}};
 sandbox.google=sdk;window.google=sdk;
 run("window.GMAPReady=true;view='map';historyAt=floodData.rows[0].observedAt;heatMode='depth';heatOn=true;render()");
 assert.equal(document.querySelector('#map')!==null,true);assert.ok(panes.overlayMouseTarget.querySelector('.map-depth-label'));assert.match(panes.overlayMouseTarget.textContent,/cm/);assert.ok(paint.length>0);const labelCount=panes.overlayMouseTarget.querySelectorAll('button').length;
 run('drawFlood()');assert.equal(panes.overlayMouseTarget.querySelectorAll('button').length,labelCount);run("heatOn=false;drawFlood()");const painted=paint.length;run('drawFlood()');assert.equal(paint.length,painted);run('window.GMAPReady=false;render()');assert.equal(panes.overlayMouseTarget.children.length,0);
 document.createElement=originalCreate;delete sandbox.google;delete window.google;
});

test('sensor list opens evidence without moving the map camera',()=>{let moves=0;sandbox.testMap={getCenter:()=>({lat:13.81,lng:100.73}),getZoom:()=>14,remove(){},flyTo(){moves++}};run("floodData.rows=[{id:'click',name:'Click road',lat:area().lat,lng:area().lng,depth:20,observedAt:Date.now()-86400000}];historyAt=null;navigate('map');map=testMap");const row=document.querySelector('[data-sensor]');row.onclick();assert.equal(moves,0);assert.equal(dialog.open,true);dialog.close();run('map=null');delete sandbox.testMap});
test('old heat is explicit and does not change sensor freshness',()=>{run("navigate('map');historyAt=null;heatOn=true;render()");const toggle=document.querySelector('#oldHeatToggle');assert.equal(toggle.hasAttribute('checked'),false);toggle.checked=true;toggle.onchange({target:toggle});assert.equal(run('showOldHeat'),true);assert.match(document.querySelector('#heatStatus').textContent,/old depths/);assert.match(document.querySelector('.sensor-value').className,/stale/);run('showOldHeat=false')});
test('stock flow has one product search and no manual page-reading or backend setup',()=>{run("navigate('supplies')");assert.ok(document.querySelector('#inventorySearch'));assert.match(document.querySelector('#inventoryProvider').textContent,/Big C/);assert.equal(document.querySelector('#metadataForm'),null);assert.equal(document.querySelector('#metadataFile'),null);assert.equal(document.querySelector('#onlyRecent'),null);assert.equal(document.querySelector('.evidence-section'),null)});
test('all six compact views preserve primary controls and omit unavailable widgets',()=>{for(const lang of ['en','th'])for(const v of ['area','map','supplies','access','alerts','help']){run(`lang='${lang}';navigate('${v}')`);assert.ok(document.querySelector('.heading h1').textContent);assert.equal(document.querySelectorAll('.rail-foot p').length,0);assert.equal(document.querySelector('#watchToggle'),null);assert.equal(document.querySelector('#metadataForm'),null)}run("lang='en';navigate('map')");assert.ok(document.querySelector('#historyDate'));assert.ok(document.querySelector('#heatToggle'));run("navigate('help')");assert.equal(document.querySelectorAll('a[href^="tel:"]').length,3)});

test('automatic stock results remain online, are searchable, and stale checks lose positive availability',()=>{run("retailerData={rows:[{provider:'bigc',productName:'Water 12 bottles',productId:'stock-test',status:'available',quantity:null,scope:'online',branchName:'',checkedAt:Date.now()}],providers:[]};inventorySearch='';inventoryProvider='all';navigate('supplies')");assert.match(document.querySelector('.stock-status').textContent,/Listed in stock/);assert.match(document.querySelector('.stock-card').textContent,/branch stock unknown/);assert.equal(document.querySelector('[data-stock-trip]'),null);const search=document.querySelector('#inventorySearch');search.oninput({target:{value:'rice'}});assert.equal(document.querySelector('.stock-card'),null);run("inventorySearch='';retailerData.rows[0].checkedAt=Date.now()-3*3600000;render()");assert.match(document.querySelector('.stock-status').textContent,/Unknown/)});

test('stock card click opens a cancellable confirmation before the official product link',()=>{run("retailerData={rows:[{provider:'makro',productName:'Soap',productId:'soap',status:'available',quantity:null,scope:'online',checkedAt:Date.now(),url:'https://www.makro.pro/en/p/soap-123'}],providers:[]};inventorySearch='';inventoryProvider='all';navigate('supplies')");document.querySelector('[data-stock-open]').onclick();assert.equal(dialog.open,true);assert.match(dialog.textContent,/Soap/);assert.equal(document.querySelector('#stockContinue').getAttribute('href'),'https://www.makro.pro/en/p/soap-123');document.querySelector('#stockCancel').onclick();assert.equal(dialog.open,false);run("retailerData.rows[0].url='https://foreign.example/product';render()");const card=document.querySelector('[data-stock-open]');card.onkeydown({target:card,key:'Enter',preventDefault(){}});assert.equal(dialog.open,true);assert.equal(document.querySelector('#stockContinue'),null);assert.match(dialog.textContent,/Product link unavailable/);dialog.close()});
test('restaurant filters and menu confirmation remain in the stock flow',()=>{run("retailerData={rows:[{provider:'kfc',productName:'Zinger Burger',productId:'CAT8-26',status:'unknown',quantity:null,scope:'online',checkedAt:Date.now(),url:'https://www.kfc.co.th/menu#CAT8-26',menuListing:true,linkType:'menu'}],providers:[]};inventorySearch='';inventoryProvider='kfc';navigate('supplies')");assert.match(document.querySelector('#inventoryProvider').textContent,/KFC/);assert.match(document.querySelector('#inventoryProvider').textContent,/McDonald's/);assert.match(document.querySelector('.stock-status').textContent,/stock unknown/);document.querySelector('[data-stock-open]').onclick();assert.equal(document.querySelector('#stockContinue').textContent,'Open menu');assert.equal(document.querySelector('#stockContinue').getAttribute('href'),'https://www.kfc.co.th/menu#CAT8-26');dialog.close();run("inventoryProvider='all'")});
test('international flow supports location, proximity, event detail and all primary views',async()=>{
 const now=Date.now();sandbox.fetch=async(url)=>Response.json(String(url).includes('geocoding-api')?{results:[{name:'Paris',admin1:'Île-de-France',country:'France',country_code:'FR',latitude:48.85,longitude:2.35}]}:String(url).includes('disasters.json')?{sources:[{name:'USGS',state:'ready',checkedAt:now,rows:[{id:'eq1',type:'earthquake',title:'Test earthquake',lat:49,lng:2,at:now,magnitude:4.5,depthKm:12,source:'USGS',url:'https://earthquake.usgs.gov/report',closed:null}]}]}:responseFor(url));
 for(const f of ['disaster-core.js','international.js'])vm.runInContext(fs.readFileSync('web/'+f,'utf8'),sandbox,{filename:f});
 await new Promise(r=>setImmediate(r));
 assert.equal(document.querySelector('h1').textContent,'Disaster feed');assert.ok(document.querySelector('[data-event="eq1"]'));
 document.querySelector('#globalLocationButton').onclick();document.querySelector('#cityQuery').value='Paris';await document.querySelector('#cityForm').onsubmit({preventDefault(){}});document.querySelector('#cityResults button').onclick();assert.match(document.querySelector('.topbar').textContent,/Paris/);
 document.querySelector('#disasterRadius').onchange({target:{value:'100'}});assert.equal(document.querySelectorAll('[data-event]').length,1);document.querySelector('[data-event="eq1"]').onclick();assert.match(dialog.textContent,/Earthquake depth 12 km/);assert.match(dialog.textContent,/from your chosen location/);dialog.close();
 for(const v of ['map','access','supplies','help','feed']){document.querySelector(`[data-global-view="${v}"]`).onclick();assert.ok(document.querySelector('h1'));}
 document.querySelector('[data-global-view="help"]').onclick();assert.equal(document.querySelector('a[href="tel:112"]').textContent,'112');assert.equal(document.querySelector('a[href="tel:1669"]'),null);
 document.querySelector('[data-global-view="access"]').onclick();document.querySelector('#globalDestination').value='Paris Hospital';document.querySelector('#globalRouteForm').onsubmit({preventDefault(){}});assert.match(dialog.querySelector('a').getAttribute('href'),/origin=48.85%2C2.35/);assert.match(dialog.textContent,/disaster access unknown/);dialog.close();
 document.querySelector('[data-global-view="supplies"]').onclick();assert.equal(document.querySelector('#inventoryPanel'),null);document.querySelector('[data-place-search="Pharmacy"]').onclick();assert.match(dialog.querySelector('a').href,/Pharmacy/);dialog.close();
 run("globalLocation=null;globalRadius='all';globalView='feed';render()");assert.equal(document.querySelector('#disasterRadius option[value="100"]').hasAttribute('disabled'),true);
});
test('custom controls and automatic location identify nearby reports and respect denied permission',()=>{
 let success,failure,calls=0;sandbox.Event=window.Event;sandbox.navigator.geolocation={getCurrentPosition(a,b){calls++;success=a;failure=b}};
 run("globalMode=true;globalView='feed';globalLocation=null;globalSources=[{name:'USGS',state:'ready',checkedAt:Date.now(),rows:[{id:'near',type:'earthquake',title:'Nearby test earthquake',lat:35,lng:139,at:Date.now(),source:'USGS',url:'https://earthquake.usgs.gov/event',magnitude:4,depthKm:10,closed:null}]}];globalLoading=false;render()");
 vm.runInContext(fs.readFileSync('web/polish.js','utf8'),sandbox,{filename:'polish.js'});assert.equal(calls,1);assert.match(document.querySelector('.nearby-summary').textContent,/Finding your location/);assert.ok(document.querySelector('#disasterType').classList.contains('native-picker'));assert.equal(document.querySelectorAll('.picker-trigger').length,4);
 success({coords:{latitude:35,longitude:139}});assert.equal(run('globalRadius'),'500');assert.equal(run('globalDays'),7);assert.match(document.querySelector('.nearby-summary').textContent,/Nearby test earthquake/);assert.match(document.querySelector('#disasterRadius').closest('.custom-picker').textContent,/Within 500 km/);
 run('globalLocation=null;requestAutomaticLocation(true)');failure({code:1});assert.match(document.querySelector('.nearby-summary').textContent,/Location access is off/);const before=calls;run('requestAutomaticLocation()');assert.equal(calls,before);assert.equal(run("read('fa-auto-location',true)"),false);
 run("setGlobalLocation({lat:48.85,lng:2.35,label:'Paris',country:'FR'})");assert.equal(run("read('fa-auto-location',true)"),false);assert.ok(document.querySelector('#globalLocationButton'));
});
