import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {DOMParser,parseHTML} from 'linkedom';
const {window,document}=parseHTML(fs.readFileSync('web/index.html','utf8'));
Object.defineProperty(document,'baseURI',{value:'https://daytondeltap.github.io/flood-aid/'});
const storage=new Map(),requests=[];
const samples={rows:[{id:'node-8',osmId:8,type:'node',en:'Test Market',th:'ตลาดทดสอบ',lat:13.81,lng:100.73,kind:'store'}],retrievedAt:Date.now()};
const responseFor=url=>String(url).includes('/data/inventory.json')?{rows:[],providers:[]} : String(url).includes('/data/places-')?samples:String(url).includes('/data/flood.json')?{rows:[{id:'FL.1',name:'Test road',lat:13.811,lng:100.731,depth:12,observedAt:Date.now()}],history:[],retrievedAt:Date.now()}:String(url).includes('/api/reports')?{reports:[],signedIn:true}:String(url).includes('/api/destinations')?{destinations:[],signedIn:true}:String(url).includes('/api/route')?{routes:[{distance:2000,duration:300,coordinates:[[100.731,13.812],[100.73,13.81]]}]}:{current:{temperature_2m:29,weather_code:3,time:'2026-10-03T08:00',relative_humidity_2m:70,wind_speed_10m:5},hourly:{time:['2026-10-03T09:00'],precipitation:[2],precipitation_probability:[75]},daily:{time:['2026-10-03'],temperature_2m_min:[26],temperature_2m_max:[31],precipitation_sum:[4]}};
const dialog=document.querySelector('dialog');dialog.showModal=function(){this.open=true};dialog.close=function(){this.open=false};window.scrollTo=()=>{};window.HTMLElement.prototype.scrollIntoView=()=>{};
const fetcher=async(url,opts)=>{requests.push({url,opts});return Response.json(responseFor(url))};
class FormDataStub{constructor(form){this.items=[...form.querySelectorAll('[name]')].map(e=>[e.name||e.getAttribute('name'),e.value??''])}get(k){return this.items.find(x=>x[0]===k)?.[1]}[Symbol.iterator](){return this.items[Symbol.iterator]()}}
const sandbox={window,document,console,DOMParser,sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},URLSearchParams,clearTimeout:()=>{},navigator:{onLine:true},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setInterval:()=>0,setTimeout:()=>0,URL,Response,Request,AbortSignal,AbortController,Date,Math,JSON,Map,Set,Promise,Number,String,encodeURIComponent,fetch:fetcher,FormData:FormDataStub};
vm.createContext(sandbox);for(const file of ['config.js','core.js','app.js','upgrade.js','pages.js','inventory-core.js','inventory.js','stock-metadata.js','compact.js','google-map.js'])vm.runInContext(fs.readFileSync('web/'+file,'utf8'),sandbox,{filename:file});
const run=source=>vm.runInContext(source,sandbox);


test('Pages loads district snapshots under repository base path',async()=>{await new Promise(r=>setImmediate(r));assert.ok(requests.some(r=>String(r.url)==='https://daytondeltap.github.io/flood-aid/data/flood.json'));assert.ok(requests.some(r=>String(r.url).includes('/flood-aid/data/places-')));assert.ok(document.querySelector('#mapSettingsButton'));run("navigate('supplies')");assert.match(document.body.textContent,/Test Market/)});
test('Pages rejects shared writes without pretending to save',async()=>{await assert.rejects(run("apiJSON('/api/reports',{method:'POST'})"),/need a backend/);run('reportForm()');assert.match(dialog.textContent,/need a backend/);assert.equal(document.querySelector('#reportForm'),null)});
test('Google key entry is optional and default configuration contains no key',()=>{assert.equal(window.FLOODAID_CONFIG.googleMapsBrowserKey,'');run('mapSettings()');assert.ok(document.querySelector('#mapsKey'));assert.equal(document.querySelector('#mapsKey').type,'password');assert.match(dialog.textContent,/Maps JavaScript API/);assert.equal(window.GMAPReady,false)});

test('retailer inventory search renders unknown stock without external setup links',()=>{run("navigate('supplies')");assert.ok(document.querySelector('#inventoryPanel'));assert.match(document.querySelector('#inventoryPanel').textContent,/Stock unknown/);assert.ok(document.querySelector('#inventoryGPS'));assert.ok(document.querySelector('#inventorySearch'));assert.equal(document.querySelector('#inventoryPanel').querySelectorAll('a').length,0)});

test('historical map and sensor list use selected time beyond 24 hours',()=>{const old=Date.now()-5*86400000;run(`floodData={rows:[{id:'old',name:'Old road',lat:13.812,lng:100.731,depth:20,observedAt:${old}}],history:[],retrievedAt:Date.now()};navigate('map');setHistory(${old})`);assert.ok(Number(document.querySelector('#heatTime').getAttribute('min'))<Date.now()-4*86400000);assert.match(document.querySelector('#timeLabel').textContent,/ICT · Historical view/);assert.match(document.querySelector('.sensor-row').textContent,/20cm/);assert.equal(document.querySelector('.sensor-value').className.includes('stale'),false);run('action("heat-now")');assert.equal(document.querySelector('.sensor-value').className.includes('stale'),true);assert.match(document.querySelector('#heatStatus').textContent,/Gray = old/)});
test('district change clears old journey and key settings stay inside the app',()=>{run("accessTarget={lat:13.81,lng:100.73,label:'Old district'};historyAt=Date.now()-86400000;changeArea(1)");assert.equal(run('accessTarget'),null);assert.equal(run('historyAt'),null);run('mapSettings()');assert.ok(document.querySelector('#rememberMapsKey'));assert.equal(document.querySelector('.maps-setup'),null);dialog.close();run('changeArea(0)')});
test('Google overlay renders canvas and cm labels at historical time and cleans up on redraw',()=>{
 const panes={overlayLayer:document.createElement('div'),overlayMouseTarget:document.createElement('div')};
 const paint=[];const originalCreate=document.createElement.bind(document);
 document.createElement=(tag,...args)=>{const el=originalCreate(tag,...args);if(tag==='canvas')el.getContext=()=>({scale(){},createRadialGradient(){return {addColorStop(){}}},fillRect(){paint.push('heat')}});return el};
 class GMap{constructor(el,options){this.el=el;this.options=options;this.center=options.center;this.zoom=options.zoom}getCenter(){return {lat:()=>this.center.lat,lng:()=>this.center.lng}}getZoom(){return this.zoom}setCenter(c){this.center=c}setZoom(z){this.zoom=z}getDiv(){return {clientWidth:1000,clientHeight:600}}addListener(){}panTo(c){this.center=c}fitBounds(){}}
 class Overlay{setMap(map){if(this.map)this.onRemove();this.map=map;if(map){this.onAdd();this.draw()}}getMap(){return this.map}getPanes(){return panes}getProjection(){return {fromLatLngToDivPixel:p=>({x:p.lng()*1000,y:p.lat()*-1000})}}}
 class Shape{setMap(){}addListener(){}}
 const sdk={maps:{Map:GMap,OverlayView:Overlay,Circle:Shape,Polyline:Shape,LatLng:class{constructor(lat,lng){this.a=lat;this.b=lng}lat(){return this.a}lng(){return this.b}},ControlPosition:{RIGHT_BOTTOM:1},event:{clearInstanceListeners(){}}}};
 sandbox.google=sdk;window.google=sdk;
 run("window.GMAPReady=true;view='map';historyAt=floodData.rows[0].observedAt;heatMode='depth';heatOn=true;render()");
 assert.equal(document.querySelector('#map')!==null,true);assert.ok(panes.overlayMouseTarget.querySelector('.map-depth-label'));assert.match(panes.overlayMouseTarget.textContent,/cm/);assert.ok(paint.length>0);const labelCount=panes.overlayMouseTarget.querySelectorAll('button').length;
 run('drawFlood()');assert.equal(panes.overlayMouseTarget.querySelectorAll('button').length,labelCount);run("heatOn=false;drawFlood()");const painted=paint.length;run('drawFlood()');assert.equal(paint.length,painted);run('window.GMAPReady=false;render()');assert.equal(panes.overlayMouseTarget.children.length,0);
 document.createElement=originalCreate;delete sandbox.google;delete window.google;
});

test('sensor list opens evidence without moving the map camera',()=>{let moves=0;sandbox.testMap={getCenter:()=>({lat:13.81,lng:100.73}),getZoom:()=>14,remove(){},flyTo(){moves++}};run("floodData.rows=[{id:'click',name:'Click road',lat:area().lat,lng:area().lng,depth:20,observedAt:Date.now()-86400000}];historyAt=null;navigate('map');map=testMap");const row=document.querySelector('[data-sensor]');row.onclick();assert.equal(moves,0);assert.equal(dialog.open,true);dialog.close();run('map=null');delete sandbox.testMap});
test('old heat is explicit and does not change sensor freshness',()=>{run("navigate('map');historyAt=null;heatOn=true;render()");const toggle=document.querySelector('#oldHeatToggle');assert.equal(toggle.hasAttribute('checked'),false);toggle.checked=true;toggle.onchange({target:toggle});assert.equal(run('showOldHeat'),true);assert.match(document.querySelector('#heatStatus').textContent,/old depths/);assert.match(document.querySelector('.sensor-value').className,/stale/);run('showOldHeat=false')});
test('stock flow has one product search and no manual page-reading or backend setup',()=>{run("navigate('supplies')");assert.ok(document.querySelector('#inventorySearch'));assert.match(document.querySelector('#inventoryProvider').textContent,/Big C/);assert.equal(document.querySelector('#metadataForm'),null);assert.equal(document.querySelector('#metadataFile'),null);assert.equal(document.querySelector('#onlyRecent'),null);assert.equal(document.querySelector('.evidence-section'),null)});
test('all six compact views preserve primary controls and omit unavailable widgets',()=>{for(const lang of ['en','th'])for(const v of ['area','map','supplies','access','alerts','help']){run(`lang='${lang}';navigate('${v}')`);assert.ok(document.querySelector('.heading h1').textContent);assert.equal(document.querySelectorAll('.rail-foot p').length,0);assert.equal(document.querySelector('#watchToggle'),null);assert.equal(document.querySelector('#metadataForm'),null)}run("lang='en';navigate('map')");assert.ok(document.querySelector('#historyDate'));assert.ok(document.querySelector('#heatToggle'));run("navigate('help')");assert.equal(document.querySelectorAll('a[href^="tel:"]').length,3)});

test('automatic stock results remain online, are searchable, and stale checks lose positive availability',()=>{run("retailerData={rows:[{provider:'bigc',productName:'Water 12 bottles',productId:'stock-test',status:'available',quantity:null,scope:'online',branchName:'',checkedAt:Date.now()}],providers:[]};inventorySearch='';inventoryProvider='all';navigate('supplies')");assert.match(document.querySelector('.stock-status').textContent,/Listed in stock/);assert.match(document.querySelector('.stock-card').textContent,/branch stock unknown/);assert.equal(document.querySelector('[data-stock-trip]'),null);const search=document.querySelector('#inventorySearch');search.oninput({target:{value:'rice'}});assert.equal(document.querySelector('.stock-card'),null);run("inventorySearch='';retailerData.rows[0].checkedAt=Date.now()-3*3600000;render()");assert.match(document.querySelector('.stock-status').textContent,/Unknown/)});
