import test from 'node:test';
import assert from 'node:assert/strict';
import {hydrationStock,collectProvider,productLinks,restaurantMenu} from '../scripts/refresh-retailer-stock.mjs';
const makro={id:'makro',name:'Makro',host:'www.makro.pro',seed:'https://www.makro.pro/en/c/beverages/drinking-water',product:/^\/en\/p\//};
const bigc={id:'bigc',name:'Big C',host:'www.bigc.co.th',seed:'https://www.bigc.co.th/en/category/drinking-water',product:/^\/en\/(?:v2\/)?product\//};
const mk=v=>`<a href="/en/p/abc-123">Water 12 bottles</a><script id="__NEXT_DATA__">${JSON.stringify({props:{pageProps:{initialSearchResult:[{productId:'123',sku:'abc',titleEn:'Water 12 bottles',inStock:v,inventoryQuantity:1,packQuantity:12}]}}})}</script>`;
const bc=stock=>{const data={products:[{product_id:744,sku:'885',name:'Water pack 6',slug:'water',stock,safety_stock:0,status:1,quantity:6}],translation:{stock:'Y',name:'Stock'}};return `<a href="/en/v2/product/water.744">Water pack 6</a><script>self.__next_f.push([1,${JSON.stringify('a:'+JSON.stringify(data)+'\n')}])</script>`};
test('Makro public product flags never become pack or exact stock counts',()=>{const [r]=hydrationStock(mk(1),makro,1000);assert.equal(r.status,'available');assert.equal(r.quantity,null);assert.equal(r.scope,'online');assert.equal(r.checkedAt,1000);assert.equal(hydrationStock(mk(0),makro)[0].status,'unavailable');assert.equal(hydrationStock(mk('yes'),makro)[0].status,'unknown')});
test('Big C streamed page data is parsed without executing scripts or using safety stock as stock',()=>{const [r]=hydrationStock(bc('N'),bigc,1000);assert.equal(r.status,'unavailable');assert.equal(r.quantity,null);assert.equal(r.url,'https://www.bigc.co.th/en/v2/product/water.744');assert.equal(hydrationStock(bc('Y'),bigc)[0].status,'available');assert.equal(hydrationStock(bc('unexpected'),bigc)[0].status,'unknown')});
test('product discovery excludes foreign URLs and tracking parameters',()=>{const links=productLinks('<a href="https://evil.example/en/p/a">Foreign</a><a href="/en/p/a?tracking=1#section">Rice</a>',makro);assert.equal(links.length,1);assert.equal(links[0].url,'https://www.makro.pro/en/p/a')});
test('a blocked retailer keeps unknown availability and never refreshes old observation time',async()=>{const r=await collectProvider(makro,async()=>{throw Error('HTTP 403')},[{productName:'Old rice',status:'available',quantity:8,checkedAt:1000}],2000);assert.equal(r.provider.state,'unavailable');assert.equal(r.rows[0].status,'unknown');assert.equal(r.rows[0].quantity,null);assert.equal(r.rows[0].checkedAt,1000)});
test('known embedded products avoid separate product-page requests',async()=>{const requests=[];const r=await collectProvider(makro,async url=>{requests.push(url);return mk(1)},[],1000);assert.equal(r.rows.length,1);assert.equal(requests.length,1);assert.equal(r.provider.state,'read')});

test('Big C preorder and not-for-sale flags take precedence over a positive stock flag',()=>{const input=flag=>{const data={product_id:744,sku:'885',name:'Water',slug:'water',stock:'Y',...flag};return `<a href="/en/v2/product/water.744">Water</a><script>self.__next_f.push([1,${JSON.stringify('a:'+JSON.stringify(data)+'\n')}])</script>`};assert.equal(hydrationStock(input({not_for_sale:true}),bigc)[0].status,'unavailable');assert.equal(hydrationStock(input({is_pre_order:true}),bigc)[0].status,'preorder')});

 test('restaurant menu cards retain published product links without inventing branch stock',()=>{const p={id:'mcdonalds',host:'www.mcdonalds.co.th',seed:'https://www.mcdonalds.co.th/mcDelivery/category/burger?lang=en',product:/^\/mcDelivery\/[^/]+\/basic\//};const html='<div class="product-grid" data-title="Big Mac"><a data-href="https://www.mcdonalds.co.th/mcDelivery/burger/basic/123" data-order-item-id="123">Order</a></div><div class="product-grid" data-title="Unsafe"><a data-href="https://foreign.example/mcDelivery/burger/basic/456" data-order-item-id="456">Order</a></div>';const rows=restaurantMenu(html,p,1000);assert.equal(rows.length,1);assert.equal(rows[0].url,'https://www.mcdonalds.co.th/mcDelivery/burger/basic/123');assert.equal(rows[0].status,'unknown');assert.equal(rows[0].quantity,null);assert.equal(rows[0].menuListing,true);const k=restaurantMenu('<div id="Rice & Bowls"><div id="CAT8-26" class="plp-item-card"><div data-testid="plp-menu-card-header">Zinger Burger</div></div></div>',{id:'kfc',host:'www.kfc.co.th',seed:'https://www.kfc.co.th/menu',product:/^\/menu/},1000);assert.equal(k[0].url,'https://www.kfc.co.th/menu#CAT8-26');assert.equal(k[0].linkType,'menu')});

test('an empty restaurant page retains prior menu items as unknown at their original check time',async()=>{const old={provider:'kfc',productName:'Zinger Burger',productId:'CAT8-26',url:'https://www.kfc.co.th/menu#CAT8-26',status:'unknown',quantity:null,checkedAt:1000,menuListing:true};const r=await collectProvider({id:'kfc',host:'www.kfc.co.th',name:'KFC',seed:'https://www.kfc.co.th/menu',product:/^\/menu/},async()=>'<html><body>Menu unavailable</body></html>',[old],2000);assert.equal(r.rows.length,1);assert.equal(r.rows[0].checkedAt,1000);assert.equal(r.rows[0].sourceUnavailable,true);assert.equal(r.rows[0].status,'unknown')});
