const FRESH_MS = 60 * 60 * 1000;
const ITEMS = ['water','food','rice','instant_food','medicine','baby_products','batteries','power_banks','hygiene','pet_food','opening','access'];
function finite(v){return v!==null&&v!==''&&Number.isFinite(Number(v));}
function pointValid(lat,lng){return finite(lat)&&finite(lng)&&Number(lat)>=13.3&&Number(lat)<=14.3&&Number(lng)>=100.1&&Number(lng)<=101.3;}
function kmBetween(a,b){const r=Math.PI/180,d=(Number(b.lat)-Number(a.lat))*r,l=(Number(b.lng)-Number(a.lng))*r,x=Math.sin(d/2)**2+Math.cos(Number(a.lat)*r)*Math.cos(Number(b.lat)*r)*Math.sin(l/2)**2;return 12742*Math.atan2(Math.sqrt(x),Math.sqrt(Math.max(0,1-x)));}
function fresh(row,now=Date.now()){const age=now-Number(row.observedAt);return Number.isFinite(age)&&age>=-300000&&age<=FRESH_MS;}
function normalizeWater(body){if(!Array.isArray(body?.data))throw Error('Unexpected water feed');return body.data.flatMap(r=>{const s=r.station||{},lat=Number(s.floodroad_lat),lng=Number(s.floodroad_long),depth=Number(r.floodroad_value),observedAt=Date.parse(String(r.floodroad_datetime).replace(' ','T')+'+07:00');if(!pointValid(lat,lng)||!finite(r.floodroad_value)||depth<0||depth>500||!Number.isFinite(observedAt))return[];return[{id:String(s.floodroad_oldcode||s.id),name:s.floodroad_name?.th||String(s.id),lat,lng,depth,observedAt,district:r.geocode?.amphoe_name?.th||'',source:'BMA via ThaiWater',url:'https://www.thaiwater.net/'}]})}
function trend(current,history,now=Date.now()){if(!fresh(current,now))return {kind:'unknown',delta:null};const previous=history.filter(r=>r.id===current.id&&r.observedAt<current.observedAt&&current.observedAt-r.observedAt<=FRESH_MS*3).sort((a,b)=>b.observedAt-a.observedAt)[0];if(!previous)return {kind:'unknown',delta:null};const delta=Math.round((current.depth-previous.depth)*10)/10;return {kind:delta>=2?'rising':delta<=-2?'draining':'stable',delta,from:previous.observedAt,to:current.observedAt};}
function pointToSegmentKm(p,a,b){const cos=Math.cos(Number(p.lat)*Math.PI/180),x=Number(p.lng)*111.32*cos,y=Number(p.lat)*110.574,ax=a[0]*111.32*cos,ay=a[1]*110.574,bx=b[0]*111.32*cos,by=b[1]*110.574,dx=bx-ax,dy=by-ay,t=dx===0&&dy===0?0:Math.max(0,Math.min(1,((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy)));return Math.hypot(x-(ax+t*dx),y-(ay+t*dy));}
function assessRoute(coords,readings,reports=[],now=Date.now()){if(!Array.isArray(coords)||coords.length<2)throw Error('Route geometry required');const near=p=>{let d=Infinity;for(let i=1;i<coords.length;i++)d=Math.min(d,pointToSegmentKm(p,coords[i-1],coords[i]));return d<=.1};const sensors=readings.filter(near),recent=sensors.filter(r=>fresh(r,now)),hazards=recent.filter(r=>r.depth>0),access=reports.filter(r=>r.item==='access'&&r.status!=='available'&&r.expiresAt>now&&near(r));return {sensorCount:sensors.length,recentSensorCount:recent.length,staleCount:sensors.length-recent.length,waterPoints:hazards,accessReports:access,unknownCoverage:true,bufferMeters:100};}
function latestReports(reports,now=Date.now()){const sorted=reports.filter(r=>r.expiresAt>now).sort((a,b)=>b.observedAt-a.observedAt||b.createdAt-a.createdAt);const m=new Map();for(const r of sorted){const key=r.placeId+'|'+r.item;if(!m.has(key))m.set(key,r)}return [...m.values()]}
function validateReport(b,now=Date.now()){if(!b||!pointValid(b.lat,b.lng)||!ITEMS.includes(b.item)||!['available','limited','unavailable'].includes(b.status)||!['visitor','merchant'].includes(b.role))throw Error('Invalid report fields');if(typeof b.placeId!=='string'||!/^(?:(?:node|way|relation)-\d+|community-[0-9a-f-]{36})$/.test(b.placeId)||typeof b.placeName!=='string'||!b.placeName.trim()||b.placeName.length>160)throw Error('Select a place');const minutes=Number(b.minutesAgo);if(!Number.isInteger(minutes)||minutes<0||minutes>60)throw Error('Observation must be within 60 minutes');if(typeof b.note!=='string'||b.note.length>400)throw Error('Comment is too long');const observedAt=now-minutes*60000,expiresAt=observedAt+(['opening','access'].includes(b.item)?3600000:7200000);if(expiresAt<=now)throw Error('This observation has expired');return {...b,lat:Number(b.lat),lng:Number(b.lng),placeName:b.placeName.trim(),observedAt,expiresAt};}

window.FloodCore={FRESH_MS,ITEMS,finite,pointValid,kmBetween,fresh,normalizeWater,trend,pointToSegmentKm,assessRoute,latestReports,validateReport};