'use strict';
window.GMAPReady=false;let googleLoad=null,gObjects=[],gHeat=null;
async function enableGoogleMap(key){if(window.google?.maps?.Map&&window.GMAPReady)return;if(googleLoad)return googleLoad;googleLoad=new Promise((resolve,reject)=>{let done=false;const script=document.createElement('script');const fail=message=>{if(done)return;done=true;clearTimeout(timeout);window.GMAPReady=false;googleLoad=null;script.remove();reject(Error(message))};const timeout=setTimeout(()=>fail('Google Maps timeout'),20000);window.faGoogleReady=()=>{if(done)return;if(!window.google?.maps?.Map)return fail('Google Maps not ready');done=true;clearTimeout(timeout);window.GMAPReady=true;resolve()};window.gm_authFailure=()=>{window.GMAPReady=false;googleLoad=null;fail('Google Maps authorization failed');toast(t('Google Maps authorization failed. Check Map settings.','Google Maps ไม่อนุญาต โปรดตรวจตั้งค่าแผนที่'));if(!$('#detail').open)render()};script.id='googleMapsScript';script.src='https://maps.googleapis.com/maps/api/js?'+new URLSearchParams({key,loading:'async',callback:'faGoogleReady',v:'weekly'});script.async=true;script.onerror=()=>fail('Google Maps could not load');document.head.append(script)});return googleLoad}
const leafletInit=initMap,leafletMarkers=drawMarkers,leafletFlood=drawFlood,leafletRoutes=drawRoutes;
initMap=function(){if(!window.GMAPReady)return leafletInit();const raw=new google.maps.Map($('#map'),{center:{lat:area().lat,lng:area().lng},zoom:14,mapTypeControl:false,streetViewControl:false,fullscreenControl:true,keyboardShortcuts:true,gestureHandling:'greedy',zoomControl:true,zoomControlOptions:{position:google.maps.ControlPosition.RIGHT_BOTTOM}});gObjects=[];map={google:true,raw,remove(){gDepth?.setMap(null);gDepth=null;gObjects.forEach(o=>o.setMap?.(null));gHeat?.setMap(null);google.maps.event.clearInstanceListeners(raw);$('#map')?.replaceChildren()},getCenter(){const c=raw.getCenter();return{lat:c.lat(),lng:c.lng()}},getZoom(){return raw.getZoom()},setView(c,z){raw.setCenter(Array.isArray(c)?{lat:c[0],lng:c[1]}:c);raw.setZoom(z)},flyTo(c,z){raw.panTo(Array.isArray(c)?{lat:c[0],lng:c[1]}:c);raw.setZoom(z)},fitBounds(b){const sw=b.getSouthWest(),ne=b.getNorthEast();raw.fitBounds({south:sw.lat,west:sw.lng,north:ne.lat,east:ne.lng},45)},removeLayer(o){o?.setMap?.(null)},on(event,fn){raw.addListener(event==='zoomend'?'zoom_changed':event,e=>fn(e?.latLng?{latlng:{lat:e.latLng.lat(),lng:e.latLng.lng()}}:e))}};raw.addListener('click',e=>{if(!picking)return;const point={lat:e.latLng.lat(),lng:e.latLng.lng()};if(!FC.pointValid(point.lat,point.lng))return;if(picking==='supply'){picking=null;backendInfo();return}const p={...point,label:t('Selected map point','จุดที่เลือกบนแผนที่')};if(picking==='origin')accessOrigin=p;else accessTarget=p;picking=null;routeSeq++;routeData=[];routeState='idle';render()});drawMarkers();drawFlood();drawRoutes()};
let gPlaceLayers=[],gFloodLayers=[],gRouteLayers=[],gDepth=null;
function clearGoogleLayers(layers){layers.forEach(o=>o.setMap(null));gObjects=gObjects.filter(o=>!layers.includes(o));return []}
function googleCircle(p,style,click){const c=new google.maps.Circle({map:map.raw,center:{lat:p.lat,lng:p.lng},radius:style.radius||35,strokeWeight:style.strokeWeight||2,strokeColor:style.strokeColor||'#fff',fillColor:style.fillColor||'#164d47',fillOpacity:style.fillOpacity??.9,zIndex:style.zIndex||10});if(click)c.addListener('click',click);gObjects.push(c);return c}
drawMarkers=function(){if(!map?.google)return leafletMarkers();gPlaceLayers=clearGoogleLayers(gPlaceLayers);for(const p of places.filter(p=>enabled[p.kind]))gPlaceLayers.push(googleCircle(p,{fillColor:p.kind==='store'?'#164d47':'#458aaa',radius:35},()=>openPlace(p.id)))};
drawFlood=function(){if(!map?.google)return leafletFlood();gFloodLayers=clearGoogleLayers(gFloodLayers);gHeat?.setMap(null);gHeat=null;const rows=readAtTime(),ref=timeReference();gDepth?.setMap(null);gDepth=null;
class SensorOverlay extends google.maps.OverlayView{
 onAdd(){this.canvas=document.createElement('canvas');this.canvas.style.cssText='position:absolute;pointer-events:none;';this.getPanes().overlayLayer.append(this.canvas);this.labels=document.createElement('div');this.labels.style.cssText='position:absolute;left:0;top:0;pointer-events:none;';this.getPanes().overlayMouseTarget.append(this.labels);this.buttons=rows.map(r=>{const current=FC.fresh(r,ref),tr=FC.trend(r,floodData.history,ref),color=!current?'#66767a':heatMode==='depth'?depthColor(r.depth):tr.kind==='rising'?'#d46c3f':tr.kind==='draining'?'#3d92a5':'#6576a2';const button=document.createElement('button');button.className='map-depth-label'+(current?'':' stale');button.style.setProperty('--sensor-color',color);button.style.pointerEvents='auto';button.textContent=r.depth+' cm';button.title=r.name+' · '+stamp(r.observedAt)+' ICT';button.setAttribute('aria-label',r.name+' · '+r.depth+' cm · '+stamp(r.observedAt)+(current?'':' · '+t('Old reading','ข้อมูลเก่า')));button.onclick=e=>{e.stopPropagation();openSensor(r)};this.labels.append(button);return {r,button}})}
 draw(){const projection=this.getProjection(),raw=this.getMap();if(!projection||!raw||!this.canvas)return;const div=raw.getDiv(),w=div.clientWidth,h=div.clientHeight,center=raw.getCenter();if(!w||!h||!center)return;const origin=projection.fromLatLngToDivPixel(center);if(!origin)return;const left=origin.x-w/2,top=origin.y-h/2,c=this.canvas,dpr=Math.min(window.devicePixelRatio||1,2);c.width=Math.ceil(w*dpr);c.height=Math.ceil(h*dpr);c.style.width=w+'px';c.style.height=h+'px';c.style.left=left+'px';c.style.top=top+'px';const ctx=c.getContext('2d');if(ctx){ctx.scale(dpr,dpr);if(heatOn&&heatMode==='depth')for(const r of rows.filter(r=>FC.fresh(r,ref)&&r.depth>0)){const p=projection.fromLatLngToDivPixel(new google.maps.LatLng(r.lat,r.lng));if(!p)continue;const x=p.x-left,y=p.y-top,radius=48,g=ctx.createRadialGradient(x,y,0,x,y,radius),color=r.depth<10?'235,186,60':r.depth<30?'236,125,50':'198,48,57';g.addColorStop(0,`rgba(${color},.72)`);g.addColorStop(1,`rgba(${color},0)`);ctx.fillStyle=g;ctx.fillRect(x-radius,y-radius,radius*2,radius*2)}}for(const {r,button} of this.buttons){const p=projection.fromLatLngToDivPixel(new google.maps.LatLng(r.lat,r.lng));if(!p)continue;button.style.left=p.x+'px';button.style.top=p.y+'px';button.hidden=p.x<left-60||p.x>left+w+60||p.y<top-30||p.y>top+h+30}}
 onRemove(){this.canvas?.remove();this.labels?.remove()}
}
gDepth=new SensorOverlay();gDepth.setMap(map.raw);
if(view==='access'&&accessTarget){const h=new google.maps.Circle({map:map.raw,center:accessTarget,radius:300,strokeColor:'#497b94',strokeWeight:1,fillOpacity:.03});gFloodLayers.push(h);gObjects.push(h)}};
drawRoutes=function(){if(!map?.google)return leafletRoutes();gRouteLayers=clearGoogleLayers(gRouteLayers);if(view!=='access')return;for(const p of [accessOrigin||area(),accessTarget].filter(Boolean))gRouteLayers.push(googleCircle(p,{radius:35,fillColor:'#255c88',zIndex:30}));routeData.forEach((r,i)=>{const line=new google.maps.Polyline({map:map.raw,path:r.coordinates.map(c=>({lng:c[0],lat:c[1]})),strokeColor:i===selectedRoute?'#255c88':'#94a2b0',strokeWeight:i===selectedRoute?6:3,strokeOpacity:i===selectedRoute?.9:.55,zIndex:5});line.addListener('click',()=>{selectedRoute=i;render()});gRouteLayers.push(line);gObjects.push(line)})};
const mapAction=action;action=function(a){if(a==='locate'&&map?.google){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(p=>{map?.flyTo([p.coords.latitude,p.coords.longitude],15)},()=>toast(t('Location unavailable. Select a district instead.','ไม่สามารถหาตำแหน่งได้ โปรดเลือกเขตแทน')),{timeout:10000});return}mapAction(a)};
render();loadData();
let initialMapKey=window.FLOODAID_CONFIG?.googleMapsBrowserKey||'';try{initialMapKey=localStorage.getItem('fa-google-off')||sessionStorage.getItem('fa-google-off')?'':sessionStorage.getItem('fa-google-key')||localStorage.getItem('fa-google-key')||initialMapKey}catch{}
if(initialMapKey)enableGoogleMap(initialMapKey).then(()=>render()).catch(()=>toast(t('Google Maps unavailable; using OpenStreetMap.','Google Maps ไม่พร้อม ใช้ OpenStreetMap แทน')));
