'use strict';
window.GMAPReady=false;let googleLoad=null,gObjects=[],gHeat=null;
async function enableGoogleMap(key){if(window.google?.maps?.Map){window.GMAPReady=true;return}if(googleLoad)return googleLoad;googleLoad=new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{googleLoad=null;reject(Error('Google Maps timeout'))},20000);window.faGoogleReady=()=>{clearTimeout(timeout);window.GMAPReady=true;resolve()};window.gm_authFailure=()=>{clearTimeout(timeout);window.GMAPReady=false;googleLoad=null;reject(Error('Google Maps authorization failed'));toast(t('Google Maps authorization failed. Check Map settings.','Google Maps ไม่อนุญาต โปรดตรวจตั้งค่าแผนที่'));render()};const s=document.createElement('script');s.src='https://maps.googleapis.com/maps/api/js?'+new URLSearchParams({key,loading:'async',callback:'faGoogleReady',v:'weekly'});s.async=true;s.onerror=()=>{clearTimeout(timeout);googleLoad=null;reject(Error('Google Maps could not load'))};document.head.append(s)});return googleLoad}
const leafletInit=initMap,leafletMarkers=drawMarkers,leafletFlood=drawFlood,leafletRoutes=drawRoutes;
initMap=function(){if(!window.GMAPReady)return leafletInit();const raw=new google.maps.Map($('#map'),{center:{lat:area().lat,lng:area().lng},zoom:14,mapTypeControl:false,streetViewControl:false,fullscreenControl:false,gestureHandling:'cooperative',zoomControl:true,zoomControlOptions:{position:google.maps.ControlPosition.RIGHT_BOTTOM}});gObjects=[];map={google:true,raw,remove(){gObjects.forEach(o=>o.setMap?.(null));gHeat?.setMap(null);google.maps.event.clearInstanceListeners(raw);$('#map')?.replaceChildren()},getCenter(){const c=raw.getCenter();return{lat:c.lat(),lng:c.lng()}},getZoom(){return raw.getZoom()},setView(c,z){raw.setCenter(Array.isArray(c)?{lat:c[0],lng:c[1]}:c);raw.setZoom(z)},flyTo(c,z){raw.panTo(Array.isArray(c)?{lat:c[0],lng:c[1]}:c);raw.setZoom(z)},fitBounds(b){const sw=b.getSouthWest(),ne=b.getNorthEast();raw.fitBounds({south:sw.lat,west:sw.lng,north:ne.lat,east:ne.lng},45)},removeLayer(o){o?.setMap?.(null)},on(event,fn){raw.addListener(event==='zoomend'?'zoom_changed':event,e=>fn(e?.latLng?{latlng:{lat:e.latLng.lat(),lng:e.latLng.lng()}}:e))}};raw.addListener('click',e=>{if(!picking)return;const point={lat:e.latLng.lat(),lng:e.latLng.lng()};if(!FC.pointValid(point.lat,point.lng))return;if(picking==='supply'){picking=null;backendInfo();return}const p={...point,label:t('Selected map point','จุดที่เลือกบนแผนที่')};if(picking==='origin')accessOrigin=p;else accessTarget=p;picking=null;routeSeq++;routeData=[];routeState='idle';render()});drawMarkers();drawFlood();drawRoutes()};
let gPlaceLayers=[],gFloodLayers=[],gRouteLayers=[];
function clearGoogleLayers(layers){layers.forEach(o=>o.setMap(null));return []}
function googleCircle(p,style,click){const c=new google.maps.Circle({map:map.raw,center:{lat:p.lat,lng:p.lng},radius:style.radius||35,strokeWeight:style.strokeWeight||2,strokeColor:style.strokeColor||'#fff',fillColor:style.fillColor||'#164d47',fillOpacity:style.fillOpacity??.9,zIndex:style.zIndex||10});if(click)c.addListener('click',click);gObjects.push(c);return c}
drawMarkers=function(){if(!map?.google)return leafletMarkers();gPlaceLayers=clearGoogleLayers(gPlaceLayers);for(const p of places.filter(p=>enabled[p.kind]))gPlaceLayers.push(googleCircle(p,{fillColor:p.kind==='store'?'#164d47':'#458aaa',radius:35},()=>openPlace(p.id)))};
drawFlood=function(){if(!map?.google)return leafletFlood();gFloodLayers=clearGoogleLayers(gFloodLayers);gHeat?.setMap(null);gHeat=null;const rows=readAtTime(),ref=timeReference();if(heatOn&&heatMode==='depth'){class SensorHeat extends google.maps.OverlayView{onAdd(){this.canvas=document.createElement('canvas');this.canvas.style.cssText='position:absolute;pointer-events:none;';this.getPanes().overlayLayer.append(this.canvas)}draw(){const projection=this.getProjection(),bounds=this.getMap().getBounds();if(!bounds)return;const ne=projection.fromLatLngToDivPixel(bounds.getNorthEast()),sw=projection.fromLatLngToDivPixel(bounds.getSouthWest()),w=Math.max(1,Math.round(ne.x-sw.x)),h=Math.max(1,Math.round(sw.y-ne.y));if(w>4000||h>4000)return;const c=this.canvas;c.width=w;c.height=h;c.style.left=sw.x+'px';c.style.top=ne.y+'px';const ctx=c.getContext('2d');if(!ctx)return;for(const r of rows.filter(r=>FC.fresh(r,ref)&&r.depth>0)){const p=projection.fromLatLngToDivPixel(new google.maps.LatLng(r.lat,r.lng)),x=p.x-sw.x,y=p.y-ne.y,g=ctx.createRadialGradient(x,y,2,x,y,38);const color=r.depth<10?'235,186,60':r.depth<30?'236,125,50':'198,48,57';g.addColorStop(0,`rgba(${color},.62)`);g.addColorStop(1,`rgba(${color},0)`);ctx.fillStyle=g;ctx.fillRect(x-38,y-38,76,76)}}onRemove(){this.canvas?.remove()}}gHeat=new SensorHeat();gHeat.setMap(map.raw)}for(const r of rows){const current=FC.fresh(r,ref),tr=FC.trend(r,floodData.history,ref),color=!current?'#8b9698':heatMode==='depth'?depthColor(r.depth):tr.kind==='rising'?'#d46c3f':tr.kind==='draining'?'#3d92a5':tr.kind==='stable'?'#6576a2':'#8b9698';gFloodLayers.push(googleCircle(r,{fillColor:color,fillOpacity:current?.95:.4,radius:current?28:20,zIndex:20},()=>openSensor(r)))}if(view==='access'&&accessTarget){const h=new google.maps.Circle({map:map.raw,center:accessTarget,radius:300,strokeColor:'#497b94',strokeWeight:1,fillOpacity:.03});gFloodLayers.push(h);gObjects.push(h)}};
drawRoutes=function(){if(!map?.google)return leafletRoutes();gRouteLayers=clearGoogleLayers(gRouteLayers);if(view!=='access')return;for(const p of [accessOrigin||area(),accessTarget].filter(Boolean))gRouteLayers.push(googleCircle(p,{radius:35,fillColor:'#255c88',zIndex:30}));routeData.forEach((r,i)=>{const line=new google.maps.Polyline({map:map.raw,path:r.coordinates.map(c=>({lng:c[0],lat:c[1]})),strokeColor:i===selectedRoute?'#255c88':'#94a2b0',strokeWeight:i===selectedRoute?6:3,strokeOpacity:i===selectedRoute?.9:.55,zIndex:5});line.addListener('click',()=>{selectedRoute=i;render()});gRouteLayers.push(line);gObjects.push(line)})};
const mapAction=action;action=function(a){if(a==='locate'&&map?.google){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(p=>{map?.flyTo([p.coords.latitude,p.coords.longitude],15)},()=>toast(t('Location unavailable. Select a district instead.','ไม่สามารถหาตำแหน่งได้ โปรดเลือกเขตแทน')),{timeout:10000});return}mapAction(a)};
render();loadData();
let initialMapKey=window.FLOODAID_CONFIG?.googleMapsBrowserKey||'';try{initialMapKey=sessionStorage.getItem('fa-google-off')?'':sessionStorage.getItem('fa-google-key')||initialMapKey}catch{}
if(initialMapKey)enableGoogleMap(initialMapKey).then(()=>render()).catch(()=>toast(t('Google Maps unavailable; using OpenStreetMap.','Google Maps ไม่พร้อม ใช้ OpenStreetMap แทน')));
